name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-11.0, macos-10.15]
    steps:
    - uses: actions/checkout@v2
    - name: version
      run: gcc --version
    - name: no-trigger
      run: gcc -Wstrict-overflow=2 -O3 -o t t.c
    - name: trigger
      run: gcc -DTRIGGER -Wstrict-overflow=2 -O3 -o t t.c
